wirenboard/wb-releases

releases.yaml

Отличия от `http://releases.contactless.ru/stable/stretch stretch`:
* не добавлены пакеты `*~dbgsym` и `*~dbg`;
* не добавлен пакет-заглушка `busybox-syslogd`;
* не добавлены старые пакеты `linux-*`;
* не добавлен переходный пакет `wb-homa-modbus`;
* не добавлены старые версии `lirc` и ещё некоторые старые contrib-пакеты для wb5;
* добавлены пакеты `wb-suite`, `wb-essential` и `wb-update-manager`.
Дифф между старым репозиторием и этим релизом: https://quickdiff.net/?unique_id=E0480FE9-9ECE-A556-09B0-DF7AA234FADE

release: wb-2104

---

releases.yaml

Для wb5 сломаны зависимости test-suite, не хватает wb-mqtt-adc. Вернул старую версию для wb5

use older test-suite for wb5

---

releases.yaml

wb-2108 is currenly linked neither to stable nor testing in order to prevent testing downgrades.
It is almost the same as testing, only kernel and some wb-mqtt-serial templates are kept back.
wb-2108 will be available by name in repository after merging, but will not break other releases currently published.

wb-2108: release candidate

---

releases.yaml

Выпускаем новый модем WBC-2G v.2
Ему нужен (но на самом деле, не критически) новый hwconf
@Boris-wb (похоже, менеджер проекта) хочет, чтобы hwconf с новым модемом попал в стейбл

backported wb-hwconf-manager for sim800c-ds support

---

releases.yaml

wb-mqtt-serial сделан бэкпортом, чтобы не тянуть wb-mqtt-confed в зависимостях

wb-2110-rc: minor translations update

---

releases.yaml

Прошивка собрана и лежит в main
http://fw-releases.wirenboard.com/fw/by-signature/mrgbw/main/3.0.0.wbfw

WB-MRGBW-D firmware updated to 3.0.0

---

releases.yaml

Это вот как раз исправление прошивки для устройств которые уже есть у клиентов и которые производство хочет запустить.

wb-2201: fix MCM8 stable firmware version

---

releases.yaml

фиксы нестабильной работы lan-чипов на wb6.9
забыл ручку в dts, что приводило к странному поведению вида "один из 5 lan-чипов неправильно стартует в ядре 5.10", т.к. не срабатывала подкапотная магия с клоками/ресетом

linux-image-wb6 5.10.35-wb8 => 5.10.35-wb9 (unstable-eth fixup)

---

releases.yaml

Зависит от https://github.com/wirenboard/u-boot-private/pull/22

wb-2201: update u-boot-wb7 to 2021.10+wb1.1.1

---

releases.yaml

Прошивка для MR2mini-old версии 1.15.1 уже не влезает в 12K (16K FLASH - 4K bootloader)

wb-2201: fix mr2m firmware version

---

releases.yaml

предполагаю, господа эмбеддеры удалили прошивку для mrwm2 с s3
(когда это произошло - неизвестно)
если я во всём правильно разобрался - wbci всё радостно кушал из-за неработавшей логики проверки. Теперь - ругается)
=> предлагаю пока закомментить mrwm2 в релизе

fws for mrwm2 temporary removed from fw-releases

---

releases.yaml

Таргет msw3G419 был добавлен в 4.17.0, однако позже к нему прикручивали калибровки датчика освещенности.
Стабильная прошивка в папке stable была 4.17.4, но в систему релизов вообще забыли добавить таргет.
Производство случайно прошило последнюю прошивку 4.18.2 из main на партию v4.20A/D в которой не было звука и движения.
Позже в партии v4.20A проявилась проблема с остановкой показаний датчика движения (на самом деле всех каналов АЦП) которая была исправлена в 4.18.3.
Не стали делать 4.17.4+wb1, зашили в партию v4.20A исправленную но не очень проверенную 4.18.3.

wb-2201: msw3G419 stable 4.18.3

---

releases.yaml

Починит проблему с созданием сертификатов на некоторых контроллерах, где ATECC отвечает дольше нужного

wb-2201: update atecc-util to 0.4.6 and libateccssl1.1 to 0.2.2

---

releases.yaml

Добавляет в релиз wb-2204 правки в cryptoauthlib, которые исправляют работу с чипом в состоянии, когда watchdog почти готов сработать и времени на обработку запроса не хватит. Проблема может возникать при долгих операциях с чипом (например, из-за медленного i/o в программе).
Исправление давно используется на стендах на производстве.

wb-2204: fix atecc-related utils to handle watchdog expire state properly

---

releases.yaml

Добавил bullseye как таргет, и сделал репозиторий, с которым получается собрать образ для обновления.
Этот PR пока никак не затронет нынешних пользователей, так как нет процедуры обновления на bullseye. Можно будет собрать FIT-образ testing и devenv.
Тут ещё лежат невлитые/недоделанные пакеты, но хочу сначала получить образ, на котором мы всё сможем обкатывать, и постепенно заменим пакеты на нормальные. Без этого не заработало бы, потому что там есть зависимости от stretch.
Из известных проблем - не работает переименование интерфейсов eth0/eth1 (их надо поменять местами). Решения не нашёл, раньше в stretch это работало благодаря патчу из debian. Вряд ли починят. Возможно, пора переименовать наши интерфейсы во что-нибудь вроде lan0/lan1.

wb-2207: add new release with bullseye target

---

releases.yaml

@evgeny-boger из dev-чатика (13.07) попросил бекпортировать u-boot v1.1.2 для wb7 в stable
проверил, что u-boot обновляется и пишет правильную версию при загрузке

wb-2204: u-boot(wb7) 1.1.1->1.1.2

---

releases.yaml

В bullseye-сборке вообще осталась версия homeui из прошлого stable, а в stretch просто та, что несовместима с актуальным wb-mqtt-serial (где добавились группы в списке шаблонов).
Обновил homeui до 2.41.1

wb-2207: upgrade homeui to 2.41.1

---

releases.yaml

решили убрать с s3 прошивку refu с багом (русский символ в device_signature; Женя в dev-чатике)
а в релизах - осталась прописана (в 2201)
=> на женкинсе релизы не собираются, т.к. проверяют доступность всех описанных прошивок

wb-2201: fw refu 1.0.0->1.0.1

---

releases.yaml

wb-mqtt-db-cli для bullseye (на python3; paho вместо mosquitto)

wb-2207: wb-mqtt-db-cli -> 1.3.0

---

releases.yaml

Версия 1.4.0 собрана уже для bullseye, с соответствующими зависимостями. Для stretch теперь нужно делать бэкпорты вручную, ответвившись от `release/wb-2207/wbX-stretch`.

wb-2207: release wb-mqtt-logs for bullseye

---

releases.yaml

stable: 1.1.2 => 1.3.0, i.e. 512MB autodetection support.
It's relatively safe and we need to make 512MB boards anyway,
so push it to stable
testing: 1.3.0 => 1.3.1, i.e. limiting working temperatures to
ensure safe operation of eMMC.

update wb7 u-boot

---

releases.yaml

Включает в себя пакеты из:
* https://github.com/wirenboard/wb-mqtt-knx/pull/32
* https://github.com/wirenboard/mqtt-tools/pull/2
* https://github.com/wirenboard/modbus-utils/pull/3
* https://github.com/wirenboard/wb-mqtt-confed/pull/29

wb-2207: release more bullseye packages

---

releases.yaml

Исправления из https://github.com/wirenboard/wb-hwconf-manager/pull/91, без них не проходят тесты на производстве

wb-2207: update hwconf to fixed version

---

releases.yaml

в 2207 stretch надо бы новые зависимости для test-suite
для буллзая будет отдельно, т.к. там wb-common еще не заехал пока

wb-2207: wb6/7 stretch wb-test-suite-deps 1.10.0 -> 1.12.0

---

releases.yaml

По этому списку паттернов будет собираться набор пакетов для staging-снапшотов (то есть, самые последние версии пакетов). Так мы сможем добавлять в репозиторий только те пакеты, которые нужны (в частности, это перестанет ломать сборку bullseye из-за пакетов, бэкпортированных для stretch когда-то очень давно).
Решение не самое изящное, но сходу лучше не придумалось. И оно даёт больше контроля над тем, какие пакеты у нас улетают в testing.
Зависит от https://github.com/wirenboard/wb-ci-tools/pull/13, но мерж не сломает актуальное состояние на билдсервере.

add staging patterns list

---

releases.yaml

Образ bullseye с текущим `staging` собирается, не вижу причин не разморозить его сейчас. Переход для пользователей будет сделан дальше с процедурой в wb-update-manager.

unfreeze testing for bullseye

---

releases.yaml

В новом e2fsprogs появились новые пакеты и частично переименовались старые. deb уже в репозитории, этот патч просто добавляет новые пакеты в staging.

staging: add new e2fsprogs packages from bullseye

---

releases.yaml

https://github.com/wirenboard/u-boot-private/pull/31
У некоторых WB7 обнаружилась проблема с watchdog, который срабатывал чуть раньше ожидаемого (например, 15 с против 20 ожидаемых). Из-за этого иногда контроллер не доходит до этапа загрузки, перезагружаясь по watchdog прямо в u-boot.
Этот патч добавляет в релиз последнюю версию u-boot для wb7, где это исправлено.
Исправление проверено в офисе, помогает, вроде ничего не ломается

wb-2207: update u-boot to 2021.10+wb1.4.2

---

releases.yaml

В нашем репозитории зачем-то лежит nodejs из nodesource, хотя (вроде) ничего не мешает устанавливать его напрямую. Наша версия, к тому же, не устанавливается в bullseye.
Этим коммитом я убираю nodejs из staging, при этом возможность установить его из nodesource останется (заедет в виде PR в wb-configs).

staging: ignore nodejs (use nodesource version from upstream)

---

releases.yaml

Забыли подвезти в релиз исправленный wb-mqtt-db (починили отображение дискретных сигналов), хотя homeui с исправлением заехал.

wb-2207: update wb-mqtt-db to 2.6.0

---

releases.yaml

Версия `wb1.4.3` исправляет проблему со слишком долгим ожиданием загрузки, когда вставлена флешка с образом для обновления. wb7 не затрагивает никак, но версию поднял, чтобы при необходимости сделать ещё один бэкпорт не думать об этом.
Начиная с `wb1.2.0` все изменения касались только wb7, поэтому такой шаг в версии безопасен.
Проверял на wb6.
Связанный PR: https://github.com/wirenboard/u-boot-private/pull/32

wb-2207: update u-boot to wb1.4.3

---

releases.yaml

Сделал отдельный псевдо-релиз, в котором будут те же пакеты, что в 2207, но подмешаны пакеты с информацией об обновлении на bullseye (скрипты и уведомления в консоли и homeui).
Сейчас этот псевдо-релиз назначен на testing для stretch. Когда bullseye станет стабильным, перенесём в stable.
Также сделал так, чтобы в staging не попадали переходные пакеты.

add bullseye-transition repo and assign it to testing

---

releases.yaml

https://github.com/wirenboard/wb-update-manager/pull/18

bullseye-transition: update wb-update-manager to upgrade4

---

releases.yaml

надо бекпортировать новую фильтрацию дребезга в 2207

wb-2207: wb-mqtt-gpio v2.8.4->2.8.4-wb100

---

releases.yaml

Теперь network-manager и modemmanager собираются из наших репозиториев и можно устанавливать их из staging

staging: add missing NM and MM libs

---

releases.yaml

https://github.com/wirenboard/wb-metapackages/pull/17
С версии 1.11.0 не было существенных изменений, в основном всё касалось как раз test-suite.

wb-2207: use python3-wb-test-suite-deps instead of old python2\'s

---

releases.yaml

https://github.com/wirenboard/wb-update-manager/pull/21

wb-2207-bullseye-transition: update wb-update-manager to -upgrade6

---

releases.yaml

Использовать nodejs из нашего репозитория всё же оказывается чуть удобней. При обновлении debian со stretch на bullseye в момент, когда удаляется старый пакет `python` и устанавливается `python-is-python2`, `nodejs` из нашего репозитория удаляется из-за зависимости от `python`. Новый пакет `nodejs` зависит уже от `python3`, но поскольку его нет в `staging` (а следовательно, в `testing`), мы не можем его установить. Следом за `nodejs` удаляется `zigbee2mqtt`, что нежелательно.
Я добавил последний на сегодня пакет `nodejs` в наш пул, теперь надо добавить его в `staging`, так при обновлении до bullseye не будет удаляться `zigbee2mqtt`.

staging: include nodejs from our repo

---

releases.yaml

забыли в 2207 перетащить мелкие фиксы упдатера (где он падал на разборе конфига wb-mqtt-serial)

wb-2207: wb-mcu-fw-updater* v1.5.1->1.5.1-wb100

---

releases.yaml

бекпортируем z-wave и r3a1 (новая релюшка) для производства

wb-2207 wb6/wb7: wb-hwconf-manager 1.52.7-wb101 -> 1.52.7-wb102

---

releases.yaml

not critical, so not updated in stable

fix fast modbus  scanning in MAI6

---

releases.yaml

Propagate https://github.com/wirenboard/homeui/pull/377

wb-mqtt-homeui: 2.44.4-upgrade1 → 2.44.4-upgrade2

---

releases.yaml

https://github.com/wirenboard/wb-mqtt-metrics/pull/6

wb-2207: update wb-mqtt-metrics to 1.1.0-wb100 (fix high load)

---

releases.yaml

фикс парсинга настроечек serial вокруг Невы надо бы завезти и в wb-2207
https://github.com/wirenboard/wb-mcu-fw-updater/pull/38

wb-2207: wb-mcu-fw-updater v1.5.1-wb100 -> v1.5.1-wb101

---

releases.yaml

https://github.com/wirenboard/wb-update-manager/pull/28

wb-2207-bullseye-transition: update wb-update-manager to upgrade11

---

releases.yaml

https://github.com/wirenboard/wb-update-manager/pull/29

bullseye-transition: update wb-release tool to -upgrade12

---

releases.yaml

- do not include libwbmqtt1-2 in wb-2304 (and exclude it from staging)
- up python3-mqttrpc to version with our Homepage to treat it as our package
depends on https://github.com/wirenboard/python-mqtt-rpc/pull/10

pre-release fixups

---

releases.yaml

CI пропустил в предыдущем PR неправильные версии (фикс CI: https://github.com/wirenboard/wb-ci-tools/pull/21)

wb-2207-transition: fix versions missed by CI

---

releases.yaml

починил взрывающийся modbus-scanner-rpc вот [здесь](https://github.com/wirenboard/modbus-utils-rpc/pull/12); надо в 2304

wb-2304: python3-modbus-utils-rpc v1.1.5 -> 1.1.6

---

releases.yaml

Теперь для testing снова используется снапшот-указатель `unstable.latest`, вместо `staging.latest` (починено в https://github.com/wirenboard/wirenboard/pull/140).
`unstable.latest` - это проверенный сборкой образа прошивки `staging.latest`.

unfreeze testing on Bullseye after wb-2304

---

releases.yaml

https://github.com/wirenboard/wb-utils/pull/90
https://github.com/wirenboard/wb-configs/pull/113
+ есть зависимость от u-boot wb1.5.0, потому меняю версию

wb-2304: add single-rootfs scheme support

---

releases.yaml

https://github.com/wirenboard/wb-configs/pull/114
пакеты собраны вручную в `wbdev chroot`

wb-2207: update wb-configs to 2.3.4-wb102

---

releases.yaml

```sh
root@wirenboard-A7PWH4NX ~# apt search wb-mqtt-zway
Sorting... Done
Full Text Search... Done
wb-mqtt-zway/testing 1.0.3+wb2 armhf
Wiren Board MQTT bridge for Z-Way stack compatible with WB conventions
root@wirenboard-A7PWH4NX ~# apt install wb-mqtt-zway
…
The following packages have unmet dependencies:
wb-mqtt-zway : Depends: libjsoncpp1 (>= 1.7.4) but it is not installable
Depends: libwbmqtt0 but it is not going to be installed
Depends: libjsoncpp0 but it is not installable
Depends: libwbmqtt (>= 1.3.3)
E: Unable to correct problems, you have held broken packages.
```
Аналогично с wb-mqtt-lirc.

Exclude wb-homa-zway, wb-mqtt-zway, wb-mqtt-lirc

---

releases.yaml

Propagate https://github.com/wirenboard/wb-update-manager/pull/35

wb-2207-bullseye-transition: update wb-update-manager to 1.2.5-wb1-upgrade18

---

releases.yaml

бекпортируем новую валидацию env_кеша в 2304

wb-2304: wb-utils v4.8.2-wb102 -> v4.8.2-wb103

---

releases.yaml

Propagate bugfixes:
- https://github.com/wirenboard/wb-mqtt-mbgate/pull/22
- https://github.com/wirenboard/wb-mqtt-mbgate/pull/24
- https://github.com/wirenboard/wb-mqtt-mbgate/pull/25
- https://github.com/wirenboard/libmodbus/commit/ba4a84812852022f97b773208b5e25997b5d0b1f (Fix RTU mode)

wb-2304: update wb-mqtt-mbgate to 1.5.4

---

releases.yaml

https://github.com/wirenboard/wb-mqtt-mbgate/pull/27

wb-2304: update wb-mqtt-mbgate to 1.5.5

---

releases.yaml

бекпорт зависаний хвконфа при неудачном хуке (wbc-4g-usb)

wb-2304: wb-hwconf-manager v1.57.1 -> 1.57.2

---

releases.yaml

бекпорт фикса странных значений range-контролов в homeui

wb-2304: wb-mqtt-homeui: v2.59.0-wb102 -> 2.59.0-wb103

---

releases.yaml

перетащили в 2304 вот это
https://github.com/wirenboard/homeui/pull/436

wb-2304: wb-mqtt-homeui 2.59.0-wb103 -> 2.59.0-wb104

---

releases.yaml

Бекпорт в 2304 
https://github.com/wirenboard/wb-configs/commit/5bdcc6f6dc6e34453d43cfc0f624c82d05f50fd2
https://github.com/wirenboard/wb-configs/pull/127
первый забыли в releases прописать, кажется

wb-2304: wb-configs 3.13.1-wb104 -> 3.13.1-wb106

---

releases.yaml

wb-2304: update wb-mqtt-serial to 2.81.0-wb102
fws: make WB-MS*, WB-MCM8, WB-MAO4, WB-MIO firmwares stable
https://github.com/wirenboard/wb-mqtt-serial/pull/623

Make firmwares stable and update wb-mqtt-serial

---

releases.yaml

https://github.com/wirenboard/wb-mao4/pull/14

firmware stable WB-MAO4 2.4.1

---

releases.yaml

https://github.com/wirenboard/wb-mrgb/pull/70

WB-LED, WB-MRGBW-D: update testing firmware to 3.4.0

---

releases.yaml

бэкпорт коммита из wb-rules в котором сообщения о неполном контроле переводятся из варнинга в дебаг

Backport wb-rules warnings removing

---

releases.yaml

бекпорт починки расширения rootfs; нужно производству
https://github.com/wirenboard/wb-utils/pull/118

wb-2307: wb-utils 4.12.0-wb101 -> 4.12.0-wb102

---

releases.yaml

В патче поддержка нормальной работы с rpmb, которую мы так и не отдали в апстрим.
Пакет mmc-utils я пропатчил и собрал руками, патч от прошлой версии подошёл. Проверили с ним инициализацию, работает.

add patched mmc-utils to staging and wb-2307

---

releases.yaml

https://github.com/wirenboard/wb-mqtt-serial/pull/646

Move WB-LED 3.4.0 firmware to stable

---

releases.yaml

Bugfixes:
* https://github.com/wirenboard/homeui/pull/471
* https://github.com/wirenboard/homeui/pull/475
* https://github.com/wirenboard/homeui/pull/476
* https://github.com/wirenboard/homeui/pull/477
* https://github.com/wirenboard/homeui/pull/478

wb-2307: update wb-mqtt-homeui to 2.75.11

---

releases.yaml

Следующие пакеты удалены из релиза:
``` 
mqtt-logger: 1.8.9
libwbmqtt: 1.7.2
libwbmqtt-dev: 1.7.2
libwbmqtt0: 1.7.2
python-json-rpc: 1.9.2.wb1
python-mqttrpc: 1.1.2
python-wb-common: 1.4.0
python-wb-mcu-fw-updater: 1.5.2
wb-homa-ninja-bridge: 1.9.1
wb-mqtt-spl-meter: 1.1.1
wb-mqtt-timestamper: 1.10.1
```

Add wb-2310

---

releases.yaml

It is replaced by modbus-utils-rpc

wb-2310: remove python3-modbus-utils-rpc

---

releases.yaml

wb-essential 1.17.4 -> 1.18.0
wb-ble-tesliot 1.1.0 -> 1.1.1
mqtt-tools 1.4.2 -> 1.4.3
wb-nm-helper 1.29.3 -> 1.29.4
wb-essential с прошивками для bluetooth
https://github.com/wirenboard/mqtt-tools/pull/6
https://github.com/wirenboard/wb-ble-tesliot/pull/10
https://github.com/wirenboard/wb-nm-helper/pull/86

wb-2310: update packages

---

releases.yaml

https://github.com/wirenboard/wb-embedded-controller/pull/23

wb-2310: update wb-ec-firmware to 1.1.0

---

releases.yaml

```
wb-mqtt-serial (2.106.3) 
* Fix port reopen after connection errors
wb-mqtt-serial (2.106.2)
* Add NEVA MT 324 third and forth tariffs reading
wb-mqtt-serial (2.106.1)
* Fix fast modbus packets reading error
wb-mqtt-serial (2.106.0)
* Add new template for Komfovent
```
Считаю, 2.106.1 и 2.106.3 очень важными, но смысл делать бэкпорт из-за промежуточных шаблонов не вижу. Поэтому просто двигаю версию

wb-2310: wb-mqtt-serial 2.105.0 -> 2.106.3

---

releases.yaml

https://github.com/wirenboard/wb-mqtt-gpio/pull/56

wb-2310: update wb-mqtt-gpio to 2.12.3

---

releases.yaml

выкатили новую версию mplc4-oni-plc-w

wb-2307-cb8ea449: mplc4-oni-plc-w v1.3.3.15475->1.3.3.15735

---

Jenkinsfile

Временно сломалась сборка репозитория с прошивками, отключаю её, чтобы софт не тормозить

temporarily disable firmware publishing

---

releases.yaml

Добавляет новый таргет `wb8/bullseye` и архитектуру arm64 в staging.
Связанный PR (сборка пакетов): https://github.com/wirenboard/wirenboard/pull/174

add arm64 to arch list + add wb8/bullseye target

---

releases.yaml

https://github.com/wirenboard/wb-mao4/pull/19
https://github.com/wirenboard/libwbmcu-periph/pull/168

WB-MAO4: testing firmware 2.4.3 -> 2.4.4 (#19)

---

releases.yaml

https://github.com/wirenboard/wb-hwconf-manager/pull/111/
https://github.com/wirenboard/linux/pull/164/
Ещё плюсом https://github.com/wirenboard/linux/pull/162/, там фикс определения microsd в бутлете на wb7.3+

wb-2310: fix 1-Wire to DI mode switch on wb74+

---

releases.yaml

https://github.com/wirenboard/wb-mrgb/pull/73

WB-LED: testing firmware 3.4.1 -> 3.4.2 (#73)

---

releases.yaml

* wb-nm-helper 1.29.5 -> 1.31.1
* wb-mqtt-homeui: 2.75.14-wb100 -> 2.75.14-wb101
https://github.com/wirenboard/homeui/pull/495
Соответсвующие доработки в wb-nm-helper заехали в 1.31.0, но раз уж поднимать версию, то и багфикс работы со старыми /etc/network/interfaces тоже подтянул

wb-2310: wb-nm-helper, wb-mqtt-homeui update

---

releases.yaml

В staging попали пакеты, собранные для wb-2207, тут их явно исключаю

staging: remove wb-cloud-agent designed for wb-2207

---

releases.yaml

https://github.com/wirenboard/wb-cloud-agent/pull/9
https://github.com/wirenboard/wb-cloud-agent/pull/8
https://github.com/wirenboard/wb-cloud-agent/pull/7

wb-2310: update wb-cloud-agent to 1.2.8

---

releases.yaml

https://github.com/wirenboard/wb-mrgb/pull/75

WB-LED: testing firmware 3.4.2 -> 3.4.3 (#75)

---

releases.yaml

Всё сломалось из-за этого пакета ещё в конце прошлого года (но на wb6 и в тестинге), сейчас это только может ухудшить совместимость при использовании обновления через debug network с кнопки, потому что factory bootlet заводит debug network на hi-speed, что в нашем allwinner не работает с некоторыми USB хостами.
Еррату я напишу (там ничего супер критичного), но пакет этот вынесу совсем из staging и из релиза, от него получилось больше вреда, чем пользы.

wb-2401: remove extra bootlet package

---

releases.yaml

Бэкпорт https://github.com/wirenboard/wb-cloud-agent/pull/13

wb-cloud-agent version bump

---

releases.yaml

Бэкпорт https://github.com/wirenboard/wb-cloud-agent/pull/13

wb-cloud-agent version bump (wb-2401)

---

releases.yaml

Забыли поднять тут https://github.com/wirenboard/wb-releases/pull/571

wb-2207: wb-cloud-agent-curl 1.2.5-wb101 → 1.2.5-wb102

---

releases.yaml

https://github.com/wirenboard/homeui/pull/516

wb-2207-bullseye-transition: update homeui to -upgrade3

---

releases.yaml

https://github.com/wirenboard/wb-mrgb/pull/75

WB-LED make 3.4.3 firmware stable

---

releases.yaml

https://github.com/wirenboard/wb-mqtt-mbgate/pull/37

wb-2401: wb-mqtt-mbgate: 1.5.14 -> 1.6.0

---

releases.yaml

В https://github.com/wirenboard/wb-releases/pull/584 попало в wb-2310, вместо wb-2401.
```sh
cat releases.yaml | yq '.releases."wb-2401"."wb7/bullseye"."wb-demo-kit-configs"'
"1.6.4"
```

wb-2401: wb-demo-kit-configs 1.6.3 → 1.6.4

---

releases.yaml

https://github.com/wirenboard/wb-releases/pull/576

WB-MAI6: make 2.0.8 fw stable

---

releases.yaml

```
The following packages have unmet dependencies:
sensor-tools-scada-client : Depends: python-mqttrpc but it is not installable
E: Unable to correct problems, you have held broken packages.
```

wb-2404: drop sensor-tools-scada-client

---

releases.yaml

* https://github.com/wirenboard/wb-mqtt-logs/pull/18
* https://github.com/wirenboard/wb-mqtt-logs/pull/19

wb-2404: wb-mqtt-logs 1.4.4 → 1.4.6

---

releases.yaml

* https://github.com/wirenboard/wb-mqtt-snmp/pull/15

wb-2404: wb-mqtt-snmp 1.2.7 → 1.2.8

---

releases.yaml

Для этих пакетов ещё предстоит ревью и фиксы, сейчас это всё нужно для того, чтобы собрать fit без тестинг-сета и начать отгружать контроллеры.
Для testing и unstable не стал добавлять ничего, будет продолжать работать через тестинг-сеты, чтобы можно было быстро заливать новые версии. По мере вливания PR буду менять версии и здесь.

add stable suite for wb8 with packages from testing set

---

releases.yaml

с печалью заметил, что wb8 не прошивает EC на инициаллизации

wb8/bullseye: bump wb-ec-firmware version

---

releases.yaml

теперь светодиоды на wb8 мигают так же, как и на других wb

wb-2404 wb8: bump kernel version (fix leds blinking at startup)

---

releases.yaml

положили serial-tool и зависимости от ядра wb8 в 2404

wb-2404: wb-suite: add serial-tool

---

releases.yaml

wb8 wb-2404: add wbmz5-supercap to hwconf-manager

---

releases.yaml

Major updates:
* https://github.com/wirenboard/wb-mqtt-confed/pull/55
* https://github.com/wirenboard/wb-rules/pull/111 
Minor updates:
* https://github.com/wirenboard/wb-rules/pull/105
* https://github.com/wirenboard/wb-rules/pull/107
* https://github.com/wirenboard/wb-rules/pull/106
* https://github.com/wirenboard/wb-rules/pull/108
* https://github.com/wirenboard/wb-rules/pull/109
* https://github.com/wirenboard/wb-rules/pull/110 
* https://github.com/wirenboard/serial_tool/pull/4
* https://github.com/wirenboard/wb-modbus-ext-scanner/pull/16
* https://github.com/tailscale/tailscale/releases

wb-2404 updates

---

releases.yaml

https://github.com/tailscale/tailscale/releases/tag/v1.68.0

wb-2404: tailscale 1.66.4 → 1.68.0

---

releases.yaml

фикс модема для wb8; обсудили внутри => в релизе для wb8 будет пока так

wb-2404 wb8: add temporary wb-gsm fixup

---

releases.yaml

внутри - конфиг для wb8 и механизм подсовывания правильного board-конфига

wb8/wb-2404: wb-mqtt-homeui v2.82.1-wb101 -> v2.82.1-wb103

---

releases.yaml

Бэкпорты https://github.com/wirenboard/homeui/pull/570 и https://github.com/wirenboard/wb-configs/pull/153

homeui -> 2.82.1-wb106; wb-configs -> 3.22.1-wb102

---

releases.yaml

доделки по wb8:
ядро - ppp в конфиг; exfat и ntfs в конфиг
wb-utils: фиксы wb-gsm для wb8

wb8: backport neer-modem fixups

---

releases.yaml

backport port probe feature to wb-2404
backport cpu usage limitation for download archives feature (wb6-wb8, effective only on wb7-8)
На wb8 синхронизировал homeui с версией для wb6-wb7.

backport port probe feature to wb-2404)

---

releases.yaml

Мимо протокола без PR бэкпортировал вот эти изменения из wb-2404 в wb-2404-wb8, досадую.
https://github.com/wirenboard/wb-configs/commit/b709d1bde1006e7e16e2b4eb2177fd5c08a2695c
https://github.com/wirenboard/wb-configs/commit/38b2de57e207a21ac1f2047a44d58c1b52fdd1ac
https://github.com/wirenboard/wb-configs/commit/e49fc80fe77b5d3116804aa87750075ff12b1069

wb-configs (wb8) fast-forward to actual wb2404 features

---

releases.yaml

Если я правильно понимаю -- это должно завезти в релиз для wb8 долгожданную 20-ю ноду и zigbee2mqtt (современной версии и версии 1.18.1).

wb-2404-wb8: Change node.js to 20, add zigbee2mqtt

---

releases.yaml

https://github.com/wirenboard/wb-demo-kit-configs/pull/33
Стали использовать новый счётчик

wb2404: wb-demo-kit-configs: 1.7.6 -> 1.8.0

---

releases.yaml

* https://github.com/wirenboard/wb-mqtt-snmp/pull/17
* https://github.com/wirenboard/wb-mqtt-snmp/pull/16

wb-2404: wb-mqtt-snmp 1.2.8 → 1.3.0

---

releases.yaml

на производстве плохо прошивался вбек; порисёчили - нарисёчили, что в wb-ec-firmware-update нужен слип
https://github.com/wirenboard/wb-embedded-controller/pull/36

wb-2404: wb-ec-firmware v1.3.1 -> v1.3.2

---

releases.yaml

https://github.com/wirenboard/homeui/pull/596

wb-2404: update homeui 2.82.1-wb107 → 2.82.1-wb108

---

releases.yaml

* wb-mqtt-homeui: 2.82.1-wb108 -> 2.82.1-wb109
* wb7: wb-configs: 3.22.1-wb103 -> 3.22.1-wb104
* wb8: wb-configs: 3.23.1-wb104+1 -> 3.23.1-wb104+2
https://github.com/wirenboard/homeui/pull/593
https://github.com/wirenboard/wb-configs/pull/171
https://github.com/wirenboard/wb-configs/pull/170

wb-2404: check ports backport

---

releases.yaml

https://github.com/wirenboard/linux/pull/214 (1-wire pullup)
https://github.com/wirenboard/linux/pull/213 (nftables)
https://github.com/wirenboard/linux/pull/211 (1-wire as DI pins)
https://github.com/wirenboard/linux/pull/210 (fix poweroff)

wb-2404: wb8: update linux-image to -wb16

---

releases.yaml

* https://github.com/wirenboard/wb-mqtt-logs/pull/20

wb-2404: wb-mqtt-logs 1.4.6 → 1.4.7

---

releases.yaml

https://github.com/wirenboard/wb-mcm/pull/40

Update WB-MCM8 testing firmware to 1.6.5

---

releases.yaml

https://github.com/wirenboard/wb-mrgb/pull/82

Update WB-MRGB testing firmware to 3.4.4

---

releases.yaml

После обновления wb-ci-tools стало возможно добавлять вспомогательную архитектуру, добавил соответственно armhf для wb8.
Проверил новый репозиторий с этим списком, fit собирается, при обновлении со старого stable ничего не даунгрейдится.

Merge package lists for WB8

---

releases.yaml

поднимал версию у python3-wb-mqtt-nm-helper, а у самого хелпера - нет

wb-2407: fix wb-mqtt-nm-helper

---

releases.yaml

* https://github.com/wirenboard/modbus-utils-rpc/pull/18

wb-2407: modbus-utils-rpc 1.2.2 → 1.2.3

---

releases.yaml

https://github.com/wirenboard/linux/pull/236 и всё, что следовало за ним

wb-2407, wb-2404: stabilize linux-image-wb8

---

releases.yaml

https://github.com/wirenboard/wb-hwconf-manager/pull/125/
нужно для wb8

wb-2407, wb-2404: update wb-hwconf-manager to 1.61.1

---

releases.yaml

https://github.com/wirenboard/wb-mcm/pull/40

Update WB-MCM8 stable firmware to 1.6.5

---

releases.yaml

починили wbio-прерывания на wb8; нада в 2407
https://github.com/wirenboard/wb-hwconf-manager/pull/126

wb-2407: wb-hwconf-manager v1.61.1 -> v1.61.2

---

releases.yaml

в wb8 заехал wireguard; договорились с @webconn сделать fastforward

wb-2407: linux-image-wb8 v6.8.0-wb101 -> v6.8.0-wb103

---

releases.yaml

* https://github.com/wirenboard/wb-mcu-fw-updater/pull/77
* https://github.com/wirenboard/wb-mcu-fw-updater/pull/78

wb-2407: wb-mcu-fw-updater 1.11.0 → 1.11.2

---

releases.yaml

https://github.com/wirenboard/wb-mcu-fw-updater/pull/76
обсуждали - всё-таки, решили влить
надо бекпорт; штука полезная

wb-2407: wb-mcu-fw-updater v1.11.2 -> v1.11.3

---

releases.yaml

добавили пакет ручками какое-то время назад

wb-2407: update rapidscada to 6.3.0-1

---

releases.yaml

[
](https://github.com/wirenboard/wb-mao4/pull/27)

Update WB-MAO4(20) testing firmware to 2.6.1

---

releases.yaml

wb-mqtt-serial: https://github.com/wirenboard/wb-mqtt-serial/pull/819
WB-MDM3: https://github.com/wirenboard/wb-md/pull/53

WB-MDM3: update stable to 2.9.0; WB-2407: update wb-mqtt-serial to 2.138.1-wb106

---

releases.yaml

https://github.com/wirenboard/wb-mcm/pull/41

Update WB-MCM8 testing firmware to 1.6.6

---

releases.yaml

https://github.com/wirenboard/wb-mrgb/pull/85

Update mrgbwG and ledG testing firmware to 3.5.1

---

releases.yaml

https://github.com/wirenboard/u-boot-private/pull/52/
Женя починил убут; дальше - мы заносим в релизы и фиты

wb-2407, wb-2410: u-boot v2:2024.01+wb1.0.1 -> v2:2024.01+wb1.0.2

---

releases.yaml

для производства 851, надо занести в 2410 починенную пищалку (юбут и бутлет)

wb-2410: wb8: update uboot & bootlet to fix buzzer

---

releases.yaml

решили донести [фикс запуска звей-сервера](https://github.com/wirenboard/linux/pull/275/files) в 2410

wb-2410: kernel: v6.8.0-wb114+wb100 -> v6.8.0-wb114+wb101

---

releases.yaml

нашли-починили [весьма неприятную багу](https://github.com/wirenboard/wb-utils/pull/165); надо занести в релис

wb-2410: wb-utils v4.25.0 -> v4.25.1

---

releases.yaml

https://github.com/wirenboard/wb-embedded-controller/pull/61

wb-2410: wb-ec-firmware: 2.0.1

---

releases.yaml

Откатываем прошивку wbec для WB7 до состояния wb-2407. Непонятные проблемы со спящим режимом

wb-2410: wb7: wb-ec-firmware: 1.3.2

---

releases.yaml

https://github.com/wirenboard/wb-embedded-controller/pull/62
обновляю пока только для wb8, если всё ок, то позже можно и для wb7 обновить

wb-2410: wb8: wb-ec-firmware: 2.0.2

---

releases.yaml

Продублировала пакеты ядра потому что в wb7/bullseye есть пакет mplc4-wirenboard7, а тут его не должно быть
mplc4-oni-plc-w закинула через upload deb
wb-mqtt-homeui https://github.com/wirenboard/homeui/pull/670
wb-utils https://github.com/wirenboard/wb-utils/pull/166
wb-suite https://github.com/wirenboard/wb-metapackages/pull/37
wb-mqtt-serial https://github.com/wirenboard/wb-mqtt-serial/pull/838

Add vendor packages

---

releases.yaml

оказывается, я не донёс новую initramfs в бутлет в предыдущем PR
(а надо)

wb-2410: wb8 update bootlet to new initramfs

---

releases.yaml

заносим в wb-2410 вот [ето](https://github.com/wirenboard/linux/pull/282)

wb-2410 wb8: kernel v6.8.0-wb114+wb102 -> v6.8.0-wb114+wb103

---

releases.yaml

надо занести быстрый [костылёк](https://github.com/wirenboard/wb-utils/pull/168)

wb-2410-cb8ea449: wb-utils v4.25.1-cb8ea449 -> v4.25.1-cb8ea449-1

---

releases.yaml

https://github.com/wirenboard/wb-mai6/pull/19

WB-MAI6: Update stable firmware to 2.1.2

---

releases.yaml

Интеграции попросили не включать сценарии, поэтому в релизе поставила версию для wb-suite 1.19.0 вместо текущей 1.19.1. 
Надо помимо wb-suite понижать версии у остальных пакетов из метапэкиджа тоже, потому что тогда релизную ветку не поставить

Fix all metapackages versions

---

releases.yaml

https://github.com/wirenboard/wb-mai6/pull/16

WB-MAI6: update testing firmware to 2.1.3

---

releases.yaml

выяяснилось что из за правок по сд карте вб8 начинает потреблять в 2 раза больше мощности, пока не выпускаем это в релиз

Revert SD in linux

---

releases.yaml

https://github.com/wirenboard/wb-mrgb/pull/86

WB-LED: update testing firmware to 3.5.2

---

releases.yaml

https://github.com/wirenboard/wb-device-manager/pull/57

wb-2501: wb-device-manager: 1.16.1 -> 1.16.2

---

releases.yaml

Завезли в hwconf возможность настройки вендорских модулей. Теперь нужно это доложить во все релизы, в тч кастомный. Бекпорты решили не делать, допом идет один коммит с добавлением usb оверлея на вб 8 https://github.com/wirenboard/wb-hwconf-manager/pull/136
Также еще докинула вендорские правки по homeui

Add hwconf custom settings

---

releases.yaml

https://github.com/wirenboard/wb-releases/pull/834

Update WB-MAI6 stable firmware to 2.1.3

---

releases.yaml

https://github.com/wirenboard/wb-releases/pull/841
https://github.com/wirenboard/wb-mqtt-serial/pull/868

Update WB-LED stable firmware to 2.5.2

---

releases.yaml

wb-diag-collect отваливался по rpc-таймауту на нагруженных контроллерах; теперь не отваливается (вынесли сбор диаг-архива из вызова rpc в отдельную таску)
https://github.com/wirenboard/homeui/pull/710
диаг-коллект просто подтянул
возможно, не соберется, пот homeui не влит

wb-2501: backport async wb-diag-collect

---

releases.yaml

https://github.com/wirenboard/wb-embedded-controller/pull/63

wb-2501: wb-ec-firmware: 2.0.3

---

releases.yaml

https://github.com/wirenboard/wb-mrgb/pull/87

Update WB-LED and WB-MRGBW-D testing firmware to 3.5.3

---

releases.yaml

https://github.com/wirenboard/wb-embedded-controller/pull/64
https://github.com/wirenboard/wb-mcu-fw-flasher/pull/28

wb-2501: wb-ec-firmware: 2.0.4; wb-mcu-fw-flasher: 1.4.1

---

releases.yaml

все пакетики, нужные для работы магнетометра у cb8ea449:
[сеттингз](https://github.com/wirenboard/custom-settings-cb8ea449/pull/2)
[хвконф](https://github.com/wirenboard/wb-hwconf-manager/pull/140) от релиза отличается только линтером => считаю, не надо ничего бекпортировать
[новый сервис](https://github.com/wirenboard/wb-mqtt-tlv43d/pull/1)
можно смотреть; пока не соберется - не волью

wb-2410-cb8ea449: add magnetometer-required packages

---

releases.yaml

* https://github.com/wirenboard/python-mqtt-rpc/pull/16
Чтобы в следующий релиз уже не был включен, в текущем релизе остается.

Exclude python3-json-rpc

---

releases.yaml

бекпорт [починки старта phy](https://github.com/wirenboard/linux/pull/314) на wb8
не соберется, пот https://github.com/wirenboard/linux/pull/315 еще не влито => я сам проконтролирую

wb-2501: wb8 kernel v6.8.0-wb124+wb100 -> 6.8.0-wb124+wb101

---

releases.yaml

заносим в wb-2501 [фикс wb-gen-serial для wb6](https://github.com/wirenboard/wb-common/pull/19)
не соберется, пот PR еще не влит - это я сам проконтролирую

wb-2501: python3-wb-common v2.2.4 -> v2.2.6

---

releases.yaml

37 дней в тестинге
https://github.com/wirenboard/wb-mrwm/pull/12

Update WB-MRWM2 stable firmware to 1.21.2

---

releases.yaml

https://github.com/wirenboard/wb-configs/pull/205
нашли небольшую багульку около udev

wb-2504: wb-configs v3.38.1 -> v3.38.2

---

releases.yaml

Добавлена в stable новая сигнатура для WB-MCM без EEPROM: mcm8Ge
Обновлены версии тестовых прошивок WB-MCM на 1.6.8
https://github.com/wirenboard/wb-mcm/pull/43

WB-MCM: add new signature mcm8Ge and update testing firmwares to 1.6.8

---

releases.yaml

В чате с вендором появился запрос на обновление прошивки mai6 клиента, какая то проблема с трехпроводным подключением.
Попытались обновить и updater не смог найти подходящий релиз для прошивок, тк он кастомный. Добавили релиз для прошивочек
Ошибка случилась на кастомном релизе 2410, но 2501 тоже я думаю надо добавить

Fix fw updates in releases

---

releases.yaml

Update FW versions for ONOKOM:
HT-1
AUX-1
MH-2
GR-3
MD-3
HS-3
TCL-3

Update FW versions for ONOKOM gateways

---

releases.yaml

1. Поднимаем версию wb-scenarios в стабильном релизе до 1.5.0 https://github.com/wirenboard/wb-scenarios/pull/44, в ней, сценарии скрыты в меню "конфигурационные файлы".
2. Поднимаем версию wb-homeui-backend и wb-mqtt-homeui до 2.117.11-wb100, в ней сценарии переехали в основное меню слева. https://github.com/wirenboard/homeui/pull/795
[задача в Ютрек](https://wirenboard.youtrack.cloud/issue/INT-472/Perenesti-menyu-scenariev-v-stabilnyj-2507)

wb-scenarios version up to 1.5.0

---

releases.yaml

Reverts wirenboard/wb-releases#981
Сломалась сборка master из-за другого расширения файла, откатываем и потом разберемся

Revert "Add `co2_sens_ns8: MF1.03D` firmware"

---

releases.yaml

wb-cloud-agent 1.6.5 branch
https://github.com/wirenboard/wb-cloud-agent/commit/83e40b4e34a3c7bd8a5d47530f27695664358f7b
wb-cloud-agent 1.6.2-wb100
https://github.com/wirenboard/wb-releases/commit/fdfd5a3fcaa46bf00e38ae6d60779b9a5f5ee40e

bump-wb-cloud-agent to v1.6.5

---

releases.yaml

Изменения 1.6.0 в пакете wb-scenarios были сделаны в этом PR:
https://github.com/wirenboard/wb-scenarios/pull/45

feat: backport wb-scenarios 1.6.0 to release 2507
