- releases.yaml
* updated wb-rules (2.6.3 -> 2.6.4)
* updated test-suite (1.20 -> 1.22), already used on bench
* minor fixes in wb-configs (2.0 -> 2.0.1)
* minor fixes in wb-rules-system (1.6.11 -> 1.6.12)
* minor fixes in wb-update-manager (1.0 -> 1.0.1)
> package updates 30.04

- releases.yaml
Для производства WB6.8 завтра:
- новое ядро с dts для 6.8
- новый тест-сьют
> wb6.8 support

- releases.yaml
> update wb-update-manager (#38014)

- releases.yaml
Вдогонку к #16, не поменял версию у зависимости
> fix wb-update-manager missing dependency

- releases.yaml
Разморозка testing случится следующим PR
> switch stable to wb-2108

- releases.yaml
* homeui: fix CSS cache
* diag-collect: grab 1000 lines from logs by default
> wb-2110: update homeui and diag-collect

- releases.yaml
https://github.com/wirenboard/wb-hwconf-manager/pull/65
> wb-2110: update wb-hwconf-manager to 1.43.2-wb3

- releases.yaml
https://github.com/wirenboard/wb-hwconf-manager/pull/66
> update wb-hwconf-manager to 1.43.2-wb4

- releases.yaml
кажется, упдатер с релизами пора в тестинг?
> bumped wb-mcu-fw-updater's version in wb-2201

- releases.yaml
Включает в себя изменения из #62
> add wb7/stretch target and wb-2201 list

- releases.yaml
надеюсь, последний фикс интернета в wb6.9
> wb-2201: linux-image-wb6 5.10.35-wb104 -> 5.10.35-wb105

- releases.yaml
> wb-2201: modems_rework (new kernel, hwconf, utils, dt-overlays)

- releases.yaml
поправили баги перед производством
> wb-2201: fix mrwm2G firmware version

- releases.yaml
Ждет проверки на стенде @Bugoon
> wb-2201: add firmware for WB-MRGBW-D with GD32

- releases.yaml
Влил новый упдатер
надо в тестинг
> wb-2204: wb-mcu-fw-updater 1.2.0->1.3.0

- releases.yaml
Добавил в релиз новую версию пакета wb-demo-kit-configs для совместимости с WB7.
> Added wb-demo-kit-configs 1.4.0 to release for compatibility WB7

- releases.yaml
Добавил в релиз wb-demo-kit-configs v1.5.0.
> Added wb-demo-kit-configs 1.5.0 to release

- releases.yaml
https://github.com/wirenboard/wb-configs/pull/58
> wb-2204: upgrade wb-configs to 2.3.4

- releases.yaml
also includes
* wb7: add missing drivers similar to wb6
This includes USB cameras, USB sound cards and GPIO keyboard
> add support for wb7.3 to kernel

- releases.yaml
https://github.com/wirenboard/wb-releases/pull/128
> wb-2201 and wb-2204: add new target msv2G42 for WB-MS

- releases.yaml
> added firmwares list for unstable suite

- releases.yaml
> added new target msw3Gc for WB-MS

- releases.yaml
судя по вопросу в dev-чатике, надо бекпортировать u-boot и в 2201
@evgeny-boger  в чатике ответил "да"
> wb-2201: u-boot(wb7) 1.1.1->1.1.2

- releases.yaml
> wb-2207: update wb-mqtt-serial to 2.65.0

- releases.yaml
Добавляет к bullseye репозиторий bullseye-backports (временное решение, wb-configs ещё не готов к ревью)
> wb-2207: update wb-configs in bullseye (get bullseye-backports repo)

- releases.yaml
stable:
linux-image-wb7 5.10.35-wb114 => 5.10.35-wb115+wb101+108
wb-hwconf-manager  1.50.0 => 1.50.0+wb101+1.52.4
testing:
linux-image-wb7:  5.10.35-wb116 => 5.10.35-wb118
wb-hwconf-manager  1.52.2 => 1.52.4
> errwb730001: up linux-image-wb7 and wb-hwconf-manager

- releases.yaml
бекпорт фиксов модема (simselect gpio; снятие питания при зависании) в wb-2204
> wb-2204: wb-utils 3.5.1->3.5.1-wb101 (bugfixes in wb-gsm)

- releases.yaml
Включает изменения из https://github.com/wirenboard/wb-utils/pull/52
> wb-2207: update wb-utils to 3.7.0-wb1

- releases.yaml
хотим бекпортировать wb-gsm в 2207
> wb-2207: wb-utils 3.7.0-wb1 -> 3.7.0-wb2

- releases.yaml
к сожалению - кажется, я поломал wb-utils в wb-2207
откатываю до 3.7.0-wb1
> wb-2207: wb-utils 3.7.0-wb2 -> 3.7.0-wb3

- releases.yaml
В #223 сделал не то, вместо удаления получилось включение два раза. Удалил и явно прописал в exclude с комментарием.
> staging: remove nodejs from repo (fix after #223)

- releases.yaml
> wb-2207: wb7/stretch, wb6/stretch: wb-utils 3.7.0-wb3 -> 3.7.0-wb4

- releases.yaml
фикс гонки hwconf и networking надо бы пропихнуть в 2207
> wb-2207: wb6,wb7: wb-hwconf-manager 1.52.7-wb100 -> 1.52.7-wb101

- releases.yaml
Бэкпорт фикса с применением пользовательского конфига при обновлении фитом
> Backport wb-configs

- releases.yaml
https://github.com/wirenboard/wb-utils/pull/59
> wb-2207: update wb-utils to 3.7.0-wb105

- releases.yaml
https://github.com/wirenboard/wb-update-manager/pull/20
> wb-2207-bullseye-transition: update wb-update-manager to -upgrade5

- releases.yaml
https://github.com/wirenboard/wb-utils/pull/60
> wb-2207: update wb-utils to -wb106

- releases.yaml
Пока не добавляю его принудительно в сборку образов, но из репозитория можно будет установить.
> wb-2207: add python3-wb-test-suite-deps

- releases.yaml
https://github.com/wirenboard/wb-update-manager/pull/22
> wb-2207: update wb-update-manager to 1.2.5-wb1

- releases.yaml
https://github.com/wirenboard/linux/pull/108
https://github.com/wirenboard/wb-dt-overlays/pull/6
> wb-2207: update packages for wb7 noeth overlay support

- releases.yaml
[Ядро](https://github.com/wirenboard/linux/pull/112)
> wb-2207 wb6/wb7: linux-image-wb 5.10.35-wb120+wb101

- releases.yaml
https://github.com/wirenboard/u-boot-private/pull/33
> wb-2207: update u-boot-wb7 to -wb1.4.4

- releases.yaml
https://github.com/wirenboard/wb-diag-collect/pull/13
> wb-2207: update wb-diag-collect to 1.3.0-wb100

- releases.yaml
бекпорт libgpiod из buster в wb-2207
на wb устанавливается-работает
магию с женкинсом ручками - сделал
> wb-2207: backport gpiod & libgpiod2 from buster to stretch

- releases.yaml
бекпорт последних вокругмодемных фиксов в 2207
> wb-2207: wb-utils 3.7.0-wb106 -> 3.7.0-wb107

- git-sources.yaml
приветствуем девайс_менеджер :)
> add wb-device-manager to repos

- releases.yaml
все что 3 месяца уже пролежало релизим. пора. остальное потихоньку в ближайшие месяцы.
> stable release for [mr mcm mrgb] fw with new modbus

- releases.yaml
https://github.com/wirenboard/wb-mqtt-metrics/pull/8
> wb-2207: update wb-mqtt-metrics to -wb101

- releases.yaml
фикс торчащего наружу через eth* dnsmasq
> wb-2207: wb-configs 2.3.4-wb100 -> 2.3.4-wb101

- releases.yaml
Фикcирую версию flash-simcom-a76xx для stretch, чтобы добавить потом отдельную версию с поддержкой bullseye
> wb-2207: flash-simcom-a76xx 1.0.2

- releases.yaml
https://github.com/wirenboard/wb-update-manager/pull/31
> bullseye-transition: update wb-update-manager to ver 14

- releases.yaml
https://github.com/wirenboard/wb-update-manager/pull/32
> bullseye-transition: update wb-update-manager to -upgrade15

- releases.yaml
фикс повторного обновления из webui в случае неудачи
> wb-2304: wb-utils v4.8.0 -> v4.8.1

- git-sources.yaml
- releases.yaml
- add wb-nm-helper package to git-sources.yaml
- remove wb-configs-stretch from staging and release
> pre wb-2304 fixups

- releases.yaml
https://github.com/wirenboard/wb-configs/pull/107
> wb-2304: update wb-configs to 3.13.1-wb100

- releases.yaml
Хотим в 2304: wb-gsm с логами про MM; скрытие модемных соединений; фиксы @lostpoint-ru в переключалку (nm-helper v1.22.x)
> wb-2304: wb-utils v4.8.1 -> 4.8.2; *wb-nm-helper v1.22.0 -> 1.23.0

- releases.yaml
https://github.com/wirenboard/homeui/pull/417
https://github.com/wirenboard/wb-update-manager/pull/33
> wb-2207-transition: bump versions of special packages

- releases.yaml
https://github.com/wirenboard/wb-nm-helper/pull/59
> wb-2304: wb-nm-helper: 1.23.0 → 1.23.1

- releases.yaml
https://github.com/wirenboard/wb-diag-collect/pull/21
> wb-2304: python3-wb-diag-collect: 1.5.4 → 1.5.6

- releases.yaml
> add transcend tool

- releases.yaml
в релиз попал не очень рабочий nm-helper; сделали реверт
> wb-2301: wb-nm-helper* v1.23.1 -> 1.23.1-wb100

- releases.yaml
Коллеги хотят в стабильный релиз
> wb-2304: intrascada 5.11.40 -> 5.14.0

- releases.yaml
https://github.com/wirenboard/homeui/pull/422
> wb-2304: update wb-mqtt-homeui to 2.59.0-wb100

- releases.yaml
бекпорт починки __db файлов в libwbmqtt1 [(вот этой)](https://github.com/wirenboard/libwbmqtt1/pull/76)
> wb-2304: bump libwbmqtt1 version

- releases.yaml
https://github.com/wirenboard/wb-nm-helper/pull/63
> wb-2304: update wb-nm-helper to 1.23.1-wb101

- releases.yaml
wb-nm-helper из этого списка въехал в общий релиз
> released packages for 70549e24

- releases.yaml
Петр попросил подождать еще один бэкпорт с изменением таймаутов для мсв4
> wb-2304: backport msw4 template

- releases.yaml
https://github.com/wirenboard/wb-configs/pull/115
> wb-2207: update wb-configs to 2.3.4-wb103

- releases.yaml
https://github.com/wirenboard/modemmanager/pull/8
подкрутили проверку, на каком sim-слоте мы сейчас
> wb-2304: *modemmanager* v*-wb102 -> v*-wb103

- releases.yaml
https://github.com/wirenboard/wb-utils/pull/92
> wb-2304: update wb-utils to 4.8.2-wb101

- releases.yaml
https://github.com/wirenboard/wb-utils/pull/95
> wb-2304: update wb-utils to 4.8.2-wb102

- releases.yaml
Propagate https://github.com/wirenboard/wb-configs/pull/117
> wb-2304: update wb-configs to 3.13.1-wb103

- releases.yaml
Бэкпортирование нового публикатора
> Backport dbus publicator

- releases.yaml
https://github.com/wirenboard/linux/pull/134/
> wb-2304: update linux-image to +wb100

- releases.yaml
https://github.com/wirenboard/libmodbus/releases/tag/v3.1.6-wb1
> staging: add libmodbus*

- releases.yaml
https://github.com/wirenboard/wb-rules/pull/91
> wb-2304: update wb-rules to 2.18.2

- releases.yaml
https://github.com/wirenboard/linux/pull/135
> wb-2304: update linux to +wb101

- releases.yaml
Propagate:
* https://github.com/wirenboard/wb-diag-collect/pull/24
* https://github.com/wirenboard/wb-diag-collect/pull/25
> wb-2304: update wb-diag-collect to 1.5.9

- releases.yaml
Забыли для libmm* указать свежую версию
> wb-2304: libmm* 1.20.0-1~bpo11+1-wb102 -> 1.20.0-1~bpo11+1-wb103

- releases.yaml
Во всех релизах увеличил версию libwbmqtt1-3, чтоб не делать бэкпорты исправлений. Всё равно мы эту ветку не развиваем, только исправлем критические ошибки.
> wb-2304, wb-2207: up libwbmqtt1-3 to 3.10.0-wb101

- releases.yaml
В новой версии критические исправления по опросу CAN шины
> wb-2304: wb-mqtt-smartweb 1.2.0 -> 1.4.0

- releases.yaml
https://github.com/wirenboard/wb-map/pull/58
> Feature/map 2.6.2

- releases.yaml
https://github.com/wirenboard/wb-diag-collect/pull/26
> wb-2304: update wb-diag-collect to 1.6.0

- releases.yaml
https://github.com/wirenboard/wb-configs/pull/123
> wb-2304: update wb-configs to 3.13.1-wb104

- releases.yaml
https://github.com/wirenboard/wb-mqtt-smartweb/pull/20
> wb-2207: wb-mqtt-smartweb 1.1.1 -> 1.1.1-wb100

- releases.yaml
https://github.com/wirenboard/wb-map/pull/59
> firmware testing WB-MAP 2.6.3

- releases.yaml
https://github.com/wirenboard/wb-utils/pull/108/
> wb-2304: update wb-utils to -wb105

- releases.yaml
* https://github.com/wirenboard/wb-ble-tesliot/pull/5
* https://github.com/wirenboard/wb-ble-tesliot/pull/6
* https://github.com/wirenboard/wb-ble-tesliot/pull/7
* https://github.com/wirenboard/wb-ble-tesliot/pull/8
> wb-2304: update wb-ble-tesliot to 1.0.8

- releases.yaml
https://github.com/wirenboard/wb-mqtt-serial/pull/629
> wb-2307: update wb-mqtt-serial to 2.93.2

- releases.yaml
https://wirenboard.bitrix24.ru/company/personal/user/150/tasks/task/view/64362/
> mrwm2 rollback to 1.18.5

- releases.yaml
https://github.com/wirenboard/homeui/pull/467
> wb-2307:  wb-mqtt-homeui: 2.75.3 -> 2.75.4

- releases.yaml
> wb-mrwm2 fix 1.20.2

- releases.yaml
https://github.com/wirenboard/wb-utils/pull/106
> wb-2207: update wb-utils to 3.7.0-wb109

- releases.yaml
https://github.com/wirenboard/mqtt-tools/pull/5
> wb-2307: update mqtt-tools to 1.4.2

- releases.yaml
* https://github.com/wirenboard/wb-configs/pull/134
* https://github.com/wirenboard/wb-utils/pull/116
> wb-2307: update wb-utils to 4.12.0-wb101, wb-configs to 3.18.5-wb100

- releases.yaml
* https://github.com/wirenboard/homeui/pull/470
* https://github.com/wirenboard/homeui/pull/468
> wb-2307: update wb-mqtt-homeui to 2.75.6

- releases.yaml
> staging: include mplc4-*

- releases.yaml
> add wb-2307-a70ab64c release

- releases.yaml
https://github.com/wirenboard/wb-utils/pull/121
> wb-2207: update wb-utils to -wb110

- releases.yaml
* https://github.com/wirenboard/wb-mqtt-serial/pull/641
> wb-2307: update wb-mqtt-serial to 2.93.3-wb100

- releases.yaml
https://github.com/wirenboard/wb-utils/pull/126
https://github.com/wirenboard/wb-utils/pull/125
> wb-2307: update wb-utils to -wb105

- releases.yaml
* https://github.com/wirenboard/wb-utils/pull/127
> wb-2307-cb8ea449: update wb-utils to 4.12.0-wb105-cb8ea449

- releases.yaml
* https://github.com/wirenboard/build-zigbee2mqtt/pull/10
* https://github.com/wirenboard/build-zigbee2mqtt/pull/9
> wb-2307: update zigbee2mqtt, zigbee2mqtt-1.18.1

- releases.yaml
Обновила версию сервера и добавила пакет, который zme сделали для наших с ними кастомных фитов.
> Update z-way server, add z-way4wb

- releases.yaml
https://github.com/wirenboard/wb-utils/pull/129
> wb-2307: update wb-utils to -wb106

- releases.yaml
https://github.com/wirenboard/wb-utils/pull/130
> wb-2207: update wb-utils to -wb111

- releases.yaml
> task-wb wildcard

- releases.yaml
https://github.com/wirenboard/wb-mqtt-iec104/pull/9
> wb-2307: update wb-mqtt-iec104 to 1.1.2

- releases.yaml
https://github.com/wirenboard/wb-mrgb/pull/71
https://github.com/wirenboard/wb-mao4/pull/16
https://github.com/wirenboard/wb-ref/pull/10
https://github.com/wirenboard/wb-mio/pull/12
> Update LED, MAO4, MIO, REF-DF testing firmwares

- releases.yaml
https://github.com/wirenboard/wb-ref-carel/pull/18
> Update REF-U testing firmware to 1.4.1

- releases.yaml
https://github.com/wirenboard/wb-utils/pull/135
> wb-2307-cb8ea: update wb-utils to -1

- releases.yaml
https://github.com/wirenboard/linux/pull/152
> wb-2307: update linux-wb to +wb101

- releases.yaml
> wb-2307: update intrahouse, intrascada, tailscale

- releases.yaml
https://github.com/wirenboard/linux/pull/153
> wb-2207: wb7 kernel 5.10.35-wb120+wb101 -> 5.10.35-wb120+wb102

- releases.yaml
https://github.com/wirenboard/wb-mqtt-serial/pull/651
> wb-2207: wb-mqtt-serial: 2.68.6-wb106 -> 2.68.6-wb108

- releases.yaml
> wb-2307-cb8ea449: update mplc4-oni-plc-w to 1.3.3.14561

- releases.yaml
> Add sigrok backport

- releases.yaml
бекпорт https://github.com/wirenboard/wb-rules/pull/96
> Remove wb-rules uncomplete control messages

- releases.yaml
https://github.com/wirenboard/wb-mqtt-serial/pull/656
> wb-2307: wb-mqtt-serial: 2.93.3-wb101 -> 2.93.3-wb102

- releases.yaml
> cb8ea449: update mplc4

- releases.yaml
https://github.com/wirenboard/wb-mcm/pull/37
> mcm8 1.6.2 fix modbus scan 0x46 responce

- releases.yaml
https://github.com/wirenboard/wb-mcm/pull/38
> mcm8 1.6.3 fix garbage in responce bit fields high bits

- releases.yaml
https://github.com/wirenboard/wb-mqtt-serial/pull/665
> wb-2307: wb-mqtt-serial 2.93.3-wb102 -> 2.93.3-wb103

- releases.yaml
https://github.com/wirenboard/wb-releases/pull/483
> WB-MAO4: update stable fw 2.4.2 -> 2.4.3

- releases.yaml
* https://github.com/wirenboard/linux/pull/159
* https://github.com/wirenboard/linux/pull/160
> wb-2310: linux 5.10.35-wb151 → 5.10.35-wb153

- releases.yaml
* https://github.com/wirenboard/wb-nm-helper/pull/87
> wb-2310: wb-nm-helper 1.29.4 → 1.29.5

- releases.yaml
* https://github.com/wirenboard/homeui/pull/480
* https://github.com/wirenboard/homeui/pull/481
> wb-2310: wb-nm-homeui 2.75.12 → 2.75.14

- releases.yaml
* https://github.com/wirenboard/wb-configs/pull/141
* https://github.com/wirenboard/wb-configs/pull/142
> wb-2310: wb-configs 3.19.0 → 3.19.2

- Jenkinsfile
Когда починятся прошивки, этот PR соберётся и можно будет вливать.
> enable firmware publishing back

- releases.yaml
https://github.com/wirenboard/homeui/pull/488
> wb-2310: wb-mqtt-homeui 2.75.14 -> 2.75.14-wb100

- releases.yaml
https://github.com/wirenboard/wb-configs/pull/144
> wb-2310: wb-configs 3.19.2 - > 3.19.3

- releases.yaml
> wb-2310: tailscale 1.50.0 → 1.54.0

- releases.yaml
Fix https://github.com/wirenboard/wb-releases/pull/528
> wb-2310: python3-wb-nm-helper 1.29.5 -> 1.31.1

- releases.yaml
https://github.com/wirenboard/wb-mai6/pull/13
> Add new MAI6 signature `wb-mai6-15` with 2.0.6 firmware

- releases.yaml
https://github.com/wirenboard/wb-mai6/pull/14
> Update WB-MAI6 testing firmware to 2.0.7

- releases.yaml
https://github.com/wirenboard/linux/pull/165
https://github.com/wirenboard/linux/pull/167
https://github.com/wirenboard/linux/pull/168
> wb-2310: linux-image-wb7: 5.10.35-wb155 -> 5.10.35-wb158

- releases.yaml
> wb-2310: tailscale 1.54.0 → 1.56.1

- releases.yaml
https://github.com/wirenboard/wb-mqtt-confed/pull/48
Это надо для изменения названий модулей в web-интерфейсе
> wb-2307-cb8ea449: add wb-mqtt-confed: 1.14.0

- releases.yaml
https://github.com/wirenboard/modemmanager/pull/13
> wb-2401: ModemManager 1.20.0-1~bpo11+1-wb105 -> 1.20.0-1~bpo11+1-wb106

- releases.yaml
* https://github.com/wirenboard/atecc-util/pull/24
* https://github.com/wirenboard/wb-mqtt-dac/pull/12
> wb-2401: update atecc-util, wb-mqtt-dac

- README.md
- releases.yaml
пока не вливаю, жду новости с производства
upd: на производстве проверили
> Add new stable release

- releases.yaml
https://github.com/wirenboard/wb-cloud-agent/pull/10
> wb-2207: update wb-cloud-agent to -wb101

- releases.yaml
* https://github.com/wirenboard/wb-mqtt-serial/pull/689
> wb-2401: wb-mqtt-serial 2.108.8 → 2.108.9

- releases.yaml
> wb-2401: tailscale 1.56.1 → 1.58.0

- releases.yaml
https://github.com/wirenboard/wb-configs/pull/148
> wb-2401: wb-configs: 3.21.1 -> 3.22.0

- releases.yaml
* https://github.com/wirenboard/libwbmqtt1/pull/95
> wb-2401: libwbmqtt1-4 4.3.5 → 4.3.6

- releases.yaml
https://github.com/wirenboard/wb-mqtt-confed/pull/51
> wb-2401, wb-2307-cb8ea449: wb-mqtt-confed 1.14.0 -> 1.14.1

- releases.yaml
* https://github.com/wirenboard/wb-configs/pull/149
> wb-2401: wb-configs 3.22.0 → 3.22.1

- releases.yaml
https://github.com/wirenboard/wb-mai6/pull/15
> Update WB-MAI6 testing firmware 2.0.7 -> 2.0.8

- releases.yaml
> wb-2401: tailscale 1.58.0 → 1.60.0

- releases.yaml
https://github.com/wirenboard/arm-trusted-firmware/
> staging: add arm-trusted-firmware package

- releases.yaml
* https://github.com/wirenboard/wb-mqtt-confed/pull/49
* https://github.com/wirenboard/wb-mqtt-confed/pull/52
* https://github.com/wirenboard/wb-mqtt-confed/pull/50
* https://github.com/wirenboard/wb-mqtt-confed/pull/53
> wb-2401: wb-mqtt-confed 1.14.1 → 1.14.5

- releases.yaml
* https://github.com/wirenboard/wb-zigbee2mqtt/pull/11
* https://github.com/wirenboard/wb-zigbee2mqtt/pull/12
> wb-2401: wb-zigbee2mqtt 1.3.2 → 1.3.4

- releases.yaml
https://github.com/wirenboard/wb-utils/pull/151
> wb-utils version bump (wb-2401)

- releases.yaml
https://github.com/wirenboard/wb-mqtt-serial/pull/688
https://github.com/wirenboard/wb-mqtt-serial/pull/690
https://github.com/wirenboard/wb-mqtt-serial/pull/709
https://github.com/wirenboard/wb-mqtt-serial/pull/704
> Add WB-MWAC v2 template

- releases.yaml
https://github.com/wirenboard/wb-mqtt-serial/pull/712
> wb-mqtt-serial version bump (wb-2401)

- releases.yaml
https://github.com/wirenboard/wb-ref-carel/pull/20
> REF-U: update testing firmware to 1.4.3

- releases.yaml
https://github.com/wirenboard/linux/pull/177
> wb-2401: update linux to +wb1

- releases.yaml
https://github.com/wirenboard/wb-mqtt-serial/pull/699
https://github.com/wirenboard/wb-mao4/pull/24
> Update WB-MAO4 testing firmware to 2.5.0

- releases.yaml
> change version

- releases.yaml
> wb-2401: rapidscada 6.1.4-1 → 6.2.1-1

- releases.yaml
https://github.com/wirenboard/wb-demo-kit-configs/pull/27
> Change version wb-demo-ki-configs for release

- releases.yaml
> WB-REF-U: make 1.4.3 firmware stable

- releases.yaml
https://github.com/wirenboard/wb-demo-kit-configs/pull/27
> Change version wb-demo-ki-configs for wb-2401

- releases.yaml
https://github.com/tailscale/tailscale/releases/tag/v1.64.0
> wb-2401,wb-2404: tailscale 1.62.1 → 1.64.0

- releases.yaml
https://github.com/wirenboard/wb-mqtt-serial/pull/725
> wb-2401: wb-mqtt-serial 2.109.1-wb100 -> 2.109.1-wb101

- releases.yaml
https://github.com/wirenboard/wb-mao4/pull/25
> Update WB-MAO4 testing firmware to 2.5.1

- releases.yaml
https://github.com/wirenboard/wb-nm-helper/pull/103
> wb-2404: wb-nm-helper 1.33.1 -> 1.33.2

- releases.yaml
> fix python3-wb-nm-helper version according to wb-nm-helper

- releases.yaml
* https://github.com/wirenboard/wb-knxd-config/pull/7
> wb-2404: wb-knxd-config 1.1.2 → 1.1.3

- releases.yaml
* https://github.com/wirenboard/wb-nm-helper/pull/105
> wb-2404: wb-nm-helper 1.33.2 → 1.33.3

- releases.yaml
> wb-2404: tailscale 1.64.0 → 1.66.1

- README.md
- releases.yaml
wb6: push stable to wb-2404
wb7: push stable to wb-2404
> wb-2404 as stable

- releases.yaml
ядро и hwconf для того, чтобы работала проверка на производстве
> wb8: more production-ready kernel & hwconf

- releases.yaml
> WB-MAO4: make 2.5.1 fw stable

- releases.yaml
* https://github.com/wirenboard/wb-mqtt-knx/pull/43
> wb-2404: wb-mqtt-knx 1.12.7 → 1.12.8

- releases.yaml
https://github.com/wirenboard/wb-utils/pull/154
> wb-2404 wb8: bump wb-utils (fix debug network)

- releases.yaml
* https://github.com/wirenboard/wb-mqtt-serial/pull/745
> wb-2404: wb-mqtt-serial 2.117.2 → 2.117.2-wb100

- releases.yaml
* wb2401:  wb-mqtt-serial: 2.109.1-wb101 -> 2.109.1-wb102
* wb-2404: wb-mqtt-serial: 2.117.2-wb100 -> 2.117.2-wb101
https://github.com/wirenboard/wb-mqtt-serial/pull/747
https://github.com/wirenboard/wb-mqtt-serial/pull/748
> wb-2401, wb-2404: wb-mqtt-serial

- releases.yaml
https://github.com/wirenboard/wb-configs/pull/151
https://github.com/wirenboard/linux/pull/194
https://github.com/wirenboard/linux/pull/193
https://github.com/wirenboard/linux/pull/192
проверили на производстве
> wb-2404: wb8: update linux-image and wb-configs

- releases.yaml
https://github.com/wirenboard/homeui/pull/552
> wb-2404: update homeui to -wb100

- releases.yaml
https://github.com/wirenboard/linux/pull/196
> wb-2404: wb8: update linux-image to -wb5

- releases.yaml
* https://github.com/wirenboard/wb-demo-kit-configs/pull/28
> wb-2404: wb-demo-kit-configs 1.7.1 → 1.7.2

- releases.yaml
https://github.com/wirenboard/u-boot-private/pull/46
https://github.com/wirenboard/wb-utils/pull/155
https://github.com/wirenboard/wb-configs/pull/152
https://github.com/wirenboard/wb-hwconf-manager/pull/120
Осталось только с ядром разобраться
> wb-2404: wb8: stabilize most of the packages

- releases.yaml
https://github.com/wirenboard/homeui/pull/558
> wb-2404: wb-mqtt-homeui 2.82.1-wb100 -> 2.82.1-wb101

- releases.yaml
https://github.com/wirenboard/wb-mqtt-serial/pull/756
> wb-2404: wb-mqtt-serial 2.117.2-wb101 -> 2.118.0-wb100

- releases.yaml
> wb-2404: libwbmqtt1-4 4.4.2 → 4.5.0

- releases.yaml
> wb-2404: update mplc4 to 1.3.5.18656

- releases.yaml
https://github.com/wirenboard/linux/pull/202
> wb-2404 wb8: update kernel to -wb7

- releases.yaml
* https://github.com/wirenboard/wb-diag-collect/pull/43
> wb-2404: wb-diag-collect 1.8.10 → 1.8.11

- releases.yaml
https://github.com/wirenboard/linux/pull/199
> wb8: add wbmz5-battery support to kernel

- releases.yaml
* https://github.com/wirenboard/wb-cloud-agent/pull/26
> wb-2404: wb-cloud-agent 1.3.3 → 1.3.3-wb102

- releases.yaml
* add to wb8
* https://github.com/wirenboard/wb-zigbee2mqtt/pull/14
> wb-2404: wb-zigbee2mqtt 1.3.4 → 1.3.5

- releases.yaml
* https://github.com/wirenboard/wb-cloud-agent/pull/32
> wb-2404: wb-cloud-agent 1.3.3-wb102 → 1.3.3-wb103

- releases.yaml
https://github.com/wirenboard/wb-mai6/pull/17
https://github.com/wirenboard/wb-mqtt-serial/pull/758
https://github.com/wirenboard/wb-mqtt-serial/pull/772
> wb-2404: wb-mqtt-serial 2.118.0-wb100; WB-MAI6 fw 2.1.0

- releases.yaml
https://github.com/wirenboard/wb-mqtt-serial/pull/773
> wb-2404: wb-mqtt-serial 2.118.0-wb101 -> 2.118.0-wb102

- releases.yaml
Считывание wbec uid
https://github.com/wirenboard/wb-embedded-controller/pull/30
https://github.com/wirenboard/wb-embedded-controller/pull/31
> wb-2404: wb-ec-firmware: 1.3.1

- releases.yaml
https://github.com/wirenboard/linux/pull/209
https://github.com/wirenboard/linux/pull/206
> wb-2404: wb8: update kernel to -wb12

- releases.yaml
https://github.com/wirenboard/wb-demo-kit-configs/pull/30
https://github.com/wirenboard/wb-demo-kit-configs/pull/29
> wb-2404: update wb-demo-kit-configs to 1.7.4

- releases.yaml
* https://github.com/wirenboard/wb-metapackages/pull/35
> staging: add task-wirenboard-*

- releases.yaml
https://github.com/wirenboard/wb-demo-kit-configs/pull/31
> add new version wb-demo-kit-configs to wb-2404

- releases.yaml
https://github.com/wirenboard/wb-demo-kit-configs/pull/32
> added wb-demo-kit-configs to wb-2404 release

- releases.yaml
* https://github.com/wirenboard/wirenboard/pull/201
> wb-2404: wb8: add task-wirenboard-wb8

- releases.yaml
https://github.com/wirenboard/wb-mqtt-serial/pull/779
Нужно для demo-чемодана
> wb-2404: wb-mqtt-serial 2.118.0-wb102 -> 2.118.0-wb104

- releases.yaml
https://github.com/wirenboard/wb-rules/pull/117
> wb8: update wb-rules to 2.20.13

- releases.yaml
https://github.com/tailscale/tailscale/compare/v1.68.0...v1.70.0
> wb-2404: tailscale 1.68.0 → 1.70.0

- releases.yaml
https://github.com/wirenboard/wb-configs/pull/168/
> wb-2404: wb8: update wb-configs to 3.23.1-wb104+1

- releases.yaml
Чтобы добавить дебки из https://github.com/EdJoPaTo/mqttui/releases в нашу репу
> staging: add mqttui

- git-sources.yaml
- releases.yaml
* https://github.com/wirenboard/wb-update-manager/pull/38
* https://github.com/wirenboard/wb-update-manager/pull/39
> wb-2404: wb-update-manager 1.3.2 → 1.3.4

- releases.yaml
https://github.com/wirenboard/linux/pull/215
https://github.com/wirenboard/wb-hwconf-manager/pull/123
> wb-2404: wb8: update linux-image and wb-hwconf-manager

- releases.yaml
* https://github.com/wirenboard/wb-cloud-agent/pull/35
> wb-2404: wb-cloud-agent 1.3.3-wb103 → 1.3.3-wb104

- releases.yaml
* https://github.com/wirenboard/wb-cloud-agent/pull/36
> wb-2404: wb-cloud-agent 1.3.3-wb104 → 1.3.3-wb105

- releases.yaml
https://github.com/wirenboard/homeui/pull/601
> wb-2404: wb-mqtt-homeui: 2.82.1-wb109 -> 2.82.1-wb110

- releases.yaml
* https://github.com/wirenboard/wb-cloud-agent/pull/37
> wb-2404: wb-cloud-agent 1.3.3-wb105 → 1.3.3-wb106

- releases.yaml
Reverts wirenboard/wb-releases#710
Сломалась публикация пакетов с архитектурой all, надо будет починить wbci, пока откатываем
> Revert "Merge package lists for WB8"

- releases.yaml
This reverts commit 0b394fab4acb8c49f08021628a34b2130e09d5a9.
С прошлого раза так и не понял, что пошло не так, но сейчас началась неделя и я готов разобраться.
> Reapply "Merge package lists for WB8 (#710)" (#711)

- releases.yaml
https://github.com/wirenboard/wb-mqtt-serial/pull/801
> wb-2407: wb-mqtt-serial: 2.138.1-wb100

- README.md
- releases.yaml
> wb-2407 is stable now!

- releases.yaml
* https://github.com/wirenboard/wb-cloud-agent/pull/38
> wb-2407: wb-cloud-agent 1.5.6 → 1.5.7

- releases.yaml
https://github.com/wirenboard/wb-mqtt-opcua/pull/23
https://github.com/wirenboard/wb-mqtt-opcua/pull/22
https://github.com/wirenboard/wb-mqtt-opcua/pull/21
https://github.com/wirenboard/wb-mqtt-mbgate/pull/46
https://github.com/wirenboard/wb-mqtt-mbgate/pull/45
https://github.com/wirenboard/wb-mqtt-iec104/pull/19
https://github.com/wirenboard/wb-mqtt-iec104/pull/18
https://github.com/wirenboard/wb-mqtt-iec104/pull/17
> fix empty config handling by some services

- releases.yaml
https://github.com/wirenboard/wb-mrgb/pull/82
> Update WB-MRGB stable firmware to 3.4.4

- releases.yaml
https://github.com/wirenboard/wb-demo-kit-configs/pull/34
производству надо бы как можно скорее
> wb-2407: wb-demo-kit-configs v1.8.0 -> v1.8.1

- releases.yaml
https://gitverse.ru/welrok/wb-welrok/commit/7533eb88902dca273d18dc248bc884bb1ff74110
> wb-2407: wb-welrok 0.0.8 -> 0.0.9

- releases.yaml
https://github.com/wirenboard/wb-demo-kit-configs/pull/35
> add wb-demo-ki-configs to stable

- releases.yaml
https://github.com/wirenboard/linux/pull/243
> wb-2407: wb8: update linux to -wb104

- releases.yaml
https://github.com/wirenboard/homeui/pull/615
> wb-2407: homeui restrict-access

- releases.yaml
https://github.com/wirenboard/homeui/pull/617/files
> wb-2407: homeui system logs

- releases.yaml
> add ONOKOM ok_tcl1b fw signature

- releases.yaml
https://github.com/wirenboard/wb-mqtt-confed/pull/58
https://github.com/wirenboard/wb-rules/pull/120
> wb-2407: update wb-rules and wb-mqtt-confed

- releases.yaml
https://github.com/wirenboard/wb-mao4/pull/26
> Add WB-MAO4-20mA firmware

- releases.yaml
> staging: include nodejs*

- releases.yaml
теперь одна версия и для wb7, и для wb8
> wb-2407: wb8: zigbee2mqtt-1.18.1 1.18.1-wb101 → 1.18.1-wb103

- releases.yaml
* https://github.com/wirenboard/wb-mqtt-mbgate/pull/49
> wb-2407: wb-mqtt-mbgate 1.7.2 → 1.7.2-wb100

- releases.yaml
https://github.com/wirenboard/wb-ref/pull/12
Бага - заносим сразу в стейбл
> WB-REF-DF: update stable and testing firmware to 1.1.3

- releases.yaml
* https://github.com/wirenboard/homeui/pull/635
> add wb-2407-a70ab64c release

- releases.yaml
[
](https://github.com/wirenboard/wb-mio/pull/14)
Обновление сабмодулей MIO.
> Update WBMIO testing firmware to 1.6.4

- releases.yaml
https://tailscale.com/changelog#2024-10-10
> wb-2407: tailscale 1.74.1 → 1.76.0

- releases.yaml
> Update WB-MAO4(20) testing firmware to 2.6.2

- releases.yaml
> Add wb-2410

- releases.yaml
https://tailscale.com/changelog
> wb-2407,wb-2410: tailscale 1.76.0 → 1.76.6

- releases.yaml
https://github.com/wirenboard/linux/pull/271
> wb-2410: linux-image-wb8: 6.8.0-wb115

- releases.yaml
Инициатор хотелки - Саша Дегтярёв (подробности в [тыже)](https://t.me/c/1604363224/18069)
я поставил пакетики - ставятся
> wb-2410: intrascada/intrahouse: v5.15.29 -> v5.17.67

- releases.yaml
https://github.com/wirenboard/homeui/pull/657
> wb-2410: wb-mqtt-homeui 2.103.3 -> 2.103.3-wb100

- releases.yaml
https://github.com/wirenboard/homeui/pull/660
> wb-2410: wb-mqtt-homeui 2.103.3-wb100 -> 2.103.3-wb101

- releases.yaml
https://github.com/wirenboard/libwbmqtt1/pull/112
> wb-2410: libwbmqtt1 5.3.1 -> 5.3.2

- releases.yaml
[Backport](https://github.com/wirenboard/homeui/pull/668)
> wb-2410: fix multiple datalists

- releases.yaml
https://github.com/wirenboard/wb-mqtt-serial/pull/836
> Wb-mqtt-serial fix tests

- releases.yaml
https://github.com/wirenboard/wb-mqtt-serial/pull/837
бекпорт шаблона
> Add opentherm template

- releases.yaml
* https://github.com/wirenboard/homeui/pull/672
> wb-2410: wb-mqtt-homeui 2.103.3-wb103 → 2.103.3-wb104

- releases.yaml
https://github.com/wirenboard/wb-mqtt-serial/pull/840
> Make vendor templates searchable from wb-device-manager

- releases.yaml
https://tailscale.com/changelog
> wb-2410: tailscale 1.76.6 → 1.78.1

- releases.yaml
Интеграция с ТМИУС КП (ЦентрЭнергоАвтоматика). INT-190.
> add tm-cpps in staging include releases.yaml

- releases.yaml
https://github.com/wirenboard/wb-mai6/pull/19
> Update WB-MAI6 testing firmware to 2.1.2

- releases.yaml
https://github.com/wirenboard/wb-mqtt-serial/pull/848
> wb-2410: wb-mqtt-serial 2.146.0-wb101 -> 2.146.0-wb102

- releases.yaml
* https://github.com/wirenboard/wb-hwconf-manager/pull/133
* https://github.com/wirenboard/wb-hwconf-manager/pull/134
> wb-2410: wb-hwconf-manager 1.63.1 → 1.64.1

- releases.yaml
https://github.com/wirenboard/wb-mqtt-mbgate/pull/52
https://github.com/wirenboard/wb-mqtt-mbgate/pull/53
> wb-2410: wb-mqtt-mbgate 1.8.2 -> 1.8.4

- releases.yaml
https://github.com/wirenboard/wb-mqtt-serial/pull/851
> wb-2410: wb-mqtt-serial: 2.146.0-wb103

- releases.yaml
Коллеги попросили не выкладывать wb-сценарии, убрала их из списка пакетов и понизила версию wb-suite
> Add release 2501

- releases.yaml
https://github.com/wirenboard/wb-releases/pull/824
> WB-MIO: make 1.6.5 stable

- releases.yaml
Довезла правки, чтобы хорошо формировался changelog релиза
> Fix lintian

- README.md
- releases.yaml
> New stable wb-2501

- releases.yaml
убрала старый почтовый домент из скриптов установки фита
> Fix old logs in wb-utils

- releases.yaml
> wb-2501: zbw 1.2 → 1.2-wb1

- releases.yaml
* https://github.com/wirenboard/wb-rules/pull/139
* https://github.com/wirenboard/wb-rules/pull/137
> wb-2501: wb-rules 2.24.0 → 2.25.1

- releases.yaml
https://github.com/wirenboard/wb-mqtt-serial/pull/866
> wb-2410: wb-mqtt-serial 2.146.0-wb103 -> 2.146.0-wb105

- releases.yaml
> Add cusom settings to staging

- releases.yaml
* https://github.com/wirenboard/wb-mqtt-metrics/pull/16
> wb-2501: wb-mqtt-metrics 0.3.6 → 0.3.7

- releases.yaml
https://github.com/wirenboard/linux/pull/303
> wb-2501: kernel v5.10.35-wb173 -> 5.10.35-wb173-wb100

- releases.yaml
https://github.com/wirenboard/wb-mqtt-serial/pull/870
> wb-2501: wb-mqtt-serial: 2.153.3-wb101

- releases.yaml
https://github.com/EdJoPaTo/mqttui/blob/v0.22.0/CHANGELOG.md
> wb-2501: mqttui 0.21.1 → 0.22.0

- releases.yaml
https://github.com/wirenboard/wb-diag-collect/pull/54
> wb-2501: wb-diag-collect: 1.9.0 -> 1.9.0-wb100

- releases.yaml
https://github.com/wirenboard/wb-mqtt-serial/pull/873
> wb-2501: wb-mqtt-serial: 2.153.3-wb102

- releases.yaml
https://github.com/wirenboard/wb-mrwm/pull/12
> Update WB-MRWM2 testing firmware to 1.21.2

- releases.yaml
[чинит](https://github.com/wirenboard/custom-settings-cb8ea449/pull/3) сборку прошивки для cb8ea449
> wb-2410-cb8ea449: custom-settings-cb8ea449 v1.1.0 -> v1.1.1

- releases.yaml
https://github.com/wirenboard/wb-demo-kit-configs/pull/38
> wb-demo-kit-configs version up

- releases.yaml
https://github.com/wirenboard/wb-mao4/pull/31
> MAO4; MAO4-20: update testing firmware to 2.6.3

- releases.yaml
Ignore stretch backport of libfdt1.
> Exclude libfdt1

- releases.yaml
https://github.com/wirenboard/wb-releases/pull/883
> Update WB-LED stable firmware to 3.5.4

- releases.yaml
готовим партнерам прошивочку на wb-2501 (вместо wb-2410)
сам прослежу, что все собралось и тд
> add wb-2501-cb8ea449 release

- releases.yaml
https://tailscale.com/changelog
> wb-2501: tailscale 1.80.2 → 1.82.0

- releases.yaml
чисто для проверки гипотезы; если все будет ок - занесем москита в продакшен
> wb-2501-cb8ea449: add test mosquitto versions

- releases.yaml
очередная проверка гипотезы; пользователей не затрагивает
> wb-2501-cb8ea449: add more debug versions of mosquitto

- releases.yaml
https://github.com/wirenboard/wb-mcm/pull/42
> Update WB-MCM testing firmware to 1.6.7

- releases.yaml
https://github.com/wirenboard/wb-mio/pull/16
> Update WB-MIO testing firmware to 1.6.6

- releases.yaml
Пакет случайно протек в релиз, пробуем убрать
> Remove scenarios from wb-2504 

- releases.yaml
https://github.com/wirenboard/wb-releases/pull/894
> Update WB-MAO4 stable firmware to 2.6.3

- README.md
- releases.yaml
Выпускаем релиз как стабильный
> New stable release wb-2504

- releases.yaml
https://github.com/wirenboard/wb-ref-carel/pull/22
> Update WB-REF-U testing firmware to 1.4.5

- releases.yaml
https://github.com/wirenboard/wb-ref-carel/pull/24
> Update WB-REF-U stable firmware to 1.4.6

- releases.yaml
https://github.com/wirenboard/wb-mio/pull/17
> Update WB-MIO testing firmware to 1.6.7

- releases.yaml
https://github.com/wirenboard/wb-mr/pull/118
https://github.com/wirenboard/wb-mqtt-serial/pull/933
https://github.com/wirenboard/wb-mqtt-serial/pull/934
> wb-2504: wb-mqtt-serial: 2.160.3-wb100; mr2mncGe: 1.21.8

- releases.yaml
Бэкпорт https://github.com/wirenboard/homeui/pull/749
> wb-2504: fix homeui range on mobile resolutions

- releases.yaml
https://github.com/wirenboard/homeui/pull/754
> fix rule list loading

- releases.yaml
* https://github.com/wirenboard/wb-configs/pull/206
> wb-2504: wb-configs 3.38.2 → 3.38.3

- releases.yaml
https://github.com/wirenboard/homeui/pull/762
> fix dropdown overflow

- releases.yaml
https://github.com/wirenboard/wb-ref/pull/13
> Update WB-REF-DF stable firmware to 1.1.4

- releases.yaml
https://github.com/wirenboard/wb-ups/pull/14
> WB-UPS: update stable and testing to 1.0.1

- README.md
- releases.yaml
> New stable release wb-2507

- releases.yaml
https://github.com/wirenboard/wb-mcm/pull/44
> Update WB-MCM testing firmware to 1.7.0

- releases.yaml
https://github.com/wirenboard/wb-mrwm/pull/14
> Update WB-MRWM stable firmware to 1.22.0
